
name: workflow Snyk
on: push
jobs:
  security_snyk:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@master
      
      - name: Run Snyk IaC scan and generate SARIF file
        id: snyk_iac_scan
        continue-on-error: true # Keep the workflow running even if issues are found
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          # The snyk/actions/iac action provides the Snyk CLI, so you can run its commands directly
          snyk iac test --all-projects --sarif-file-output=snyk.sarif
          
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        if: always() # Explicitly run this step even if previous steps failed
        with:
          sarif_file: snyk.sarif
