name: workflow Snyk
on: push
jobs:
  security_synk :
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # Ensure the workflow doesn't stop on Snyk findings
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects --sarif-file-output=snyk.sarif # Adds --all-projects and redirects SARIF output to a file
          
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
