
name: workflow Snyk
on: push
jobs:
  security_snyk:
    runs-on: ubuntu-latest
    permissions: # Set permissions for the job
      security-events: write # Required to upload SARIF to code scanning
    steps:
      - uses: actions/checkout@master
      
      - name: Run Snyk to check for vulnerabilities in IaC
        uses: snyk/actions/iac@master
        id: snyk_iac_scan # Give the step an ID to reference its output
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects --sarif-file-output=snyk.sarif
          
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3 # Updated to v3
        if: steps.snyk_iac_scan.outcome == 'success' || steps.snyk_iac_scan.outcome == 'failure'
        with:
          sarif_file: snyk.sarif
